-- 전체 사원 목록
SELECT 
   EMPLOYEE_ID ID, 
   FIRST_NAME || ' ' || LAST_NAME NAME,
   SALARY sal,
   DEPARTMENT_ID dept,
   JOB_ID JOB
FROM 
   EMPLOYEES;

-- 존재하는 부서 코드
SELECT 
   DISTINCT  DEPARTMENT_ID  
FROM 
   EMPLOYEES e 
WHERE 
   DEPARTMENT_ID IS NOT NULL 
ORDER BY 1;

--- 직업검색
SELECT
	DISTINCT JOB_ID
FROM
	EMPLOYEES e ;

-- 각각의 부서의 사원들만 조회 하려고 한다,
-- SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 부서코드; 이명령이 11개가 있어야 한다.
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =20;